### ISSUE TITLE
Multiplayer achievements

### ISSUE THREAD

**Issue by Jonihonkaniemi** [OAMKPelienOhjelmointi2016/DescentRemake#47]
Erilaiset multiplayer-saavutukset, kuten killstriket.
Koko saavutuslogiikka
UI/äänet saavutuksista

**Comment by lassehav-oamk** [comment]
Eli skripti, jolla seurata pelaajan ilmavoittoputkea, tilanne nollautuu pelaajan kuollessa. Viiden ilmavoiton välein ilmoitus muille pelaajille ääniefektin kanssa "Matti 5 kills in a row!" "10 kill streak for Matti!" jne.
